name: tictactoe
description: "Tic Tac Toe technical test"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^3.0.3
  flutter_animate: ^4.5.2
  fpdart: ^1.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  custom_lint: ^0.8.1
  riverpod_generator: ^3.0.3
  analyzer: ^8.4.0
  mocktail: ^1.0.4
  fake_async: ^1.3.3
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  analyzer: ^8.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: 'SpaceMono'
      fonts:
        - asset: assets/fonts/space_mono/SpaceMono-Regular.ttf
        - asset: assets/fonts/space_mono/SpaceMono-Bold.ttf
          weight: 700
